name: Test Data Sheet AI Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    name: Test ${{ matrix.test_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: CSV Loader
            file_name: csv_loader_test.py
          - test_name: Schema Manager
            file_name: schema_manager_test.py
          - test_name: SQL Validator
            file_name: sql_validator_test.py

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install -r requirements.txt

      - name: Run Coverage Tests
        run: |
          coverage run -m pytest -v ${{ matrix.file_name }}
          coverage report