name: Test Data Sheet AI Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    name: Tests (${{ matrix.test_name }}) 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - test_name: CSV Loader
            file_name: csv_loader_test.py
          - test_name: Schema Manager
            file_name: schema_manager_test.py

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest ${{ matrix.file_name }}

      - name: Run Coverage
        run: |
          coverage run -m pytest ${{ matrix.file_name }}
          coverage report